inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'lib/monkey_patches.rb'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/HashSyntax:
  Enabled: false

# dealbreaker:
Style/TrailingCommaInLiteral:
  Enabled: false

# would require external library
Layout/IndentHeredoc:
  Enabled: false

# sane line length
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'features/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
