inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'lib/monkey_patches.rb'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/HashSyntax:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

# sane line length
Layout/LineLength:
  Max: 120
  Exclude:
    - 'features/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
